### ISSUE TITLE
i2syntax support

### ISSUE THREAD

**Issue by erikogabrielsson** [amspath/libisyntax#37] opened 2024-03-13 12:35 UTC
Hi,

Im testing libisyntax against the i2syntax available on Philips Open Pathology Portal ("20220215_161205.i2syntax" and "20220215_153758.i2syntax"). I can parse tile size properties etc but when getting tiles i get:
```
Error: isyntax_hulsken_decompress(): invalid codeblock, serialized_length too large (101580672)
```
and a blank tile as output. It is not clear from the documentation, but I guess this is because i2syntax is not supported?

Are there any supported test images publicly available?

**Comment by alex-virodov** [comment] 2024-03-13 12:52
Hello. I used the following iSyntax v1 image for development: https://zenodo.org/records/5037046#.ZAn17IDMLJU 
(from https://gitlab.com/BioimageInformaticsGroup/openphi project).

As to iSyntax v2, tldr is: not supported afaik, unless @Falcury says otherwise. 

More detail about v2:
I had someone else having a similar issue, but there the problem was in a different place. We were triggering "non-partial header blocks are not supported" here: https://github.com/amspath/libisyntax/blob/main/src/isyntax/isyntax.c#L3304
It seems that there is slightly different code path in SlideScape for that code block for v2: https://github.com/amspath/slidescape/blob/master/src/isyntax/isyntax.c#L3207
@Falcury is it possible that SlideScape supports iSyntax v2 better, and the changes were not ported back to libisyntax? I wasn't tracking any development in SlideScape/libisyntax unfortunately.

**Comment by erikogabrielsson** [comment] 2024-03-13 13:15
From what I have seen, iSyntax v2 is not the same as i2syntax.

**Comment by alex-virodov** [comment] 2024-03-13 13:25
> From what I have seen, iSyntax v2 is not the same as i2syntax.

Quite possibly, I have not encountered them enough to know how they are different inside. 

If it helps, SlideScape seems to read a version here:
https://github.com/amspath/slidescape/blob/master/src/isyntax/isyntax.c#L356
`// Value will likely be "5.0" for v1 iSyntax files, "100.5" for v2 iSyntax files`

Since the header is plain text, you can see what your file has for the xml tag PIM_DP_UFS_INTERFACE_VERSION. The file that was causing me trouble had '.isyntax' extenstion and tag:
`<Attribute Name="PIM_DP_UFS_INTERFACE_VERSION" Group="0x301d" Element="0x1001" PMSVR="IString">100.4</Attribute>`

I would be curious to know what your .i2syntax file says for this tag, if it is not too much trouble and ok to share.

**Comment by Falcury** [comment] 2024-03-16 10:06
> From what I have seen, iSyntax v2 is not the same as i2syntax.

The v2 iSyntax files from the Philips portal have a .i2syntax file extension instead of .isyntax.

> As to iSyntax v2, tldr is: not supported afaik, unless @Falcury says otherwise.

Support for the v2 iSyntax format should be considered partial right now. I only have two v2 files available to test with (the ones from the OpenPathology portal), so part of the issue is that I don't have that many example files to work with. 

Also note that there is at least one (other) known issue for the current implementation of the v2 support. For one of the v2 iSyntax files (20220215_153758.i2syntax), not all tiles load correctly in Slidescape (I'm not sure why). The file 20220215_161205.i2syntax seems to load correctly at least in Slidescape though.

I don't think I ever tested/debugged libisyntax on the v2 files. This should probably be looked into. 

> Quite possibly, I have not encountered them enough to know how they are different inside.

In a nutshell, the layout of the header is different, and the codeblocks are compressed using the 'version 2' Hulsken decompression (regular v1 iSyntax uses the 'version 1' compression scheme). 

Here is the commit where I added v2 support:
https://github.com/amspath/slidescape/commit/8c816d86f5ba3b77e6bea8a50084e19666977f5f
 
> If it helps, SlideScape seems to read a version here: https://github.com/amspath/slidescape/blob/master/src/isyntax/isyntax.c#L356 `// Value will likely be "5.0" for v1 iSyntax files, "100.5" for v2 iSyntax files`
> 
> Since the header is plain text, you can see what your file has for the xml tag PIM_DP_UFS_INTERFACE_VERSION. The file that was causing me trouble had '.isyntax' extenstion and tag: `<Attribute Name="PIM_DP_UFS_INTERFACE_VERSION" Group="0x301d" Element="0x1001" PMSVR="IString">100.4</Attribute>`
> 
> I would be curious to know what your .i2syntax file says for this tag, if it is not too much trouble and ok to share.

The publicly available files from the Philips portal are 20220215_153758.i2syntax and 20220215_161205.i2syntax. These both have the "100.5" in the header information. I have never encountered a file with "100.4" data layout. Would you be willing to share a file with this layout so I can make the necessary changes to support it?

> More detail about v2: I had someone else having a similar issue, but there the problem was in a different place. We were triggering "non-partial header blocks are not supported" here: https://github.com/amspath/libisyntax/blob/main/src/isyntax/isyntax.c#L3304 It seems that there is slightly different code path in SlideScape for that code block for v2: https://github.com/amspath/slidescape/blob/master/src/isyntax/isyntax.c#L3207 @Falcury is it possible that SlideScape supports iSyntax v2 better, and the changes were not ported back to libisyntax? I wasn't tracking any development in SlideScape/libisyntax unfortunately.

Yes it's possible that something is broken in libisyntax, I never properly tested the v2 files with it (as I mentioned above).
Note that the code is mostly identical between libisyntax and Slidescape (and kept in sync between the codebases), with the exception of libisyntax.c/h which are only used by libisyntax and not used by Slidescape.

**Comment by NGeras** [comment] 2024-03-16 10:42
> The publicly available files from the Philips portal are 20220215_153758.i2syntax and 20220215_161205.i2syntax. These both have the "100.5" in the header information. I have never encountered a file with "100.4" data layout. Would you be willing to share a file with this layout so I can make the necessary changes to support it?

I have downloaded sample files from [Phillips Knowledge Center](https://philips.mizecx.com/knowledgeDocument.html?c32dbe16978d93ecf202eefc2fa4682c99ff838b2642f7446652f9a5ca1d9b2ac58fe45516515e98f5623c93ab6891aa3932d3ecd19d372a94bd6e66700063665655a893df2fa43831cf7960248afc999c6a2f4cb6109e8a50c248e0aeacaff344dac727423b5609fec7b34f1f62ab5841b70909bdc42ded6d5b8ab1c6f04d67fae652a5e687f3184033ae0eb2c49bcb), they have .isyntax extension with "100.4" data layout and in Slidescape I encountered the same problem as with .i2syntax file I have (I can share it separately if needed).

**Comment by Falcury** [comment] 2024-03-16 10:53
> I have downloaded sample files from [Phillips Knowledge Center](https://philips.mizecx.com/knowledgeDocument.html?c32dbe16978d93ecf202eefc2fa4682c99ff838b2642f7446652f9a5ca1d9b2ac58fe45516515e98f5623c93ab6891aa3932d3ecd19d372a94bd6e66700063665655a893df2fa43831cf7960248afc999c6a2f4cb6109e8a50c248e0aeacaff344dac727423b5609fec7b34f1f62ab5841b70909bdc42ded6d5b8ab1c6f04d67fae652a5e687f3184033ae0eb2c49bcb), they have .isyntax extension with "100.4" data layout and in Slidescape I encountered the same problem as with .i2syntax file I have (I can share it separately if needed).

Thanks, I will look into this.

> Yes it's possible that something is broken in libisyntax, I never properly tested the v2 files with it (as I mentioned above).

After some testing, I found at least part of the problem. In isyntax_reader.c, isyntax_hulsken_decompress() should be passed the correct compressor version (instead of always 1), like so:
```
        isyntax_hulsken_decompress(codeblock_data, codeblock->block_size,
                                   isyntax->block_width, isyntax->block_height,
                                   codeblock->coefficient, wsi->compressor_version,
                                   is_ll ? tile->color_channels[color].coeff_ll : tile->color_channels[color].coeff_h);
```

**Comment by Falcury** [comment] 2024-03-16 11:49
I fixed two separate issues in this commit: https://github.com/amspath/libisyntax/commit/7ceca1f3eebcef1c406fd843c3e359aba3a9076b

There is still an issue with some tiles not being read properly, but most should work correctly now.

**Comment by erikogabrielsson** [comment] 2024-03-24 16:13
> I fixed two separate issues in this commit: [7ceca1f](https://github.com/amspath/libisyntax/commit/7ceca1f3eebcef1c406fd843c3e359aba3a9076b)
> 
> There is still an issue with some tiles not being read properly, but most should work correctly now.

I can now read tiles from i2syntax files, but parts of the right side of the slide looks to have some problem:
![image](https://github.com/amspath/libisyntax/assets/83275777/5f684e9c-4a8c-4032-a06f-d1769ba3c5f4)
![image](https://github.com/amspath/libisyntax/assets/83275777/4e96e5f5-1b30-4a70-8509-63d9ac92b1c3)
This is a slide converted with Wsidicomizer using [pyisyntax](https://github.com/anibali/pyisyntax) wrapper, only reading the base layer in the i2syntax file and recreating the pyramid from that.

Reading a tile in the intermediate region using pyisintax:
![image](https://github.com/amspath/libisyntax/assets/83275777/cf679fe8-7bee-407c-a620-8f09ec740b23)
I dont think it is a problem with the python wrapper, as I got the same result from my own wrapper (which is not as nice as pyisintax...)

I got the same problem with one of the philips example slides (20220215_153758.i2syntax):
![image](https://github.com/amspath/libisyntax/assets/83275777/b036b6f9-bab3-45ab-993b-c536e9402cc7)

**Comment by Falcury** [comment] 2024-03-24 17:24
Yes, this is exactly the issue I have been seeing. I expect it's in some way related to the way the codeblocks and codeblock clusters are arranged in the file (we are probably making some wrong assumptions somewhere). So far I haven't found the exact cause.

**Comment by Falcury** [comment] 2024-05-19 20:20
I finally tracked down the issue. It was an off-by-one error, causing the last codeblock cluster in the file to be skipped. The fix is here: https://github.com/amspath/libisyntax/commit/05d214f7eb33e258b79ee95af0959c0fd3141bf9

**Comment by Falcury** [comment] 2024-07-02 18:17
I am closing this as completed. Please re-open if there are still issues with the iSyntax V2 files.

**Closed as completed by Falcury** 2024-07-02 18:17 UTC
